### ISSUE TITLE
Game handle creation fails when empty .esp or .esm files are present

### ISSUE THREAD

**Issue by WrinklyNinja** [WrinklyNinja/libloadorder#12]
Reported by pStyl3 [here](http://forums.bethsoft.com/topic/1512502-rel-loot-thread-16/?p=23876693).

To replicate, download ASIS and SUM, and run SUM through Mod Organiser, choosing to sort with LOOT. During the process, LOOT will launch with the error:

> Error: Game-specific settings could not be initialised. libloadorder failed to create a game handle. Details: ASIS.esp : File is empty.

This is because a zero-byte ASIS.esp file is created before SUM runs LOOT. Ideally, the ASIS.esp created would have a TES4 header record, but libloadorder shouldn't fail when that isn't the case, it should just ignore the file, just like all other non-plugin files. In fact, it usually doesn't fail, but for some reason Mod Organiser's involvement breaks something.

It's worth noting though that this behaviour probably breaks *why* the ASIS.esp file is being created in the first place, so I should discuss this with whoever is responsible.

**Comment by WrinklyNinja** [comment]
More weirdness: the issue only happens when I run LOOT through Mod Organiser, I've updated the description to include this.

Libloadorder's tests actually test for behaviour with an empty plugin file present, so that LOOT will work when run outside of MO isn't that surprising.

**Comment by WrinklyNinja** [comment]
Hmm, now everything is working fine. I rebuilt LOOT to make sure it was using the latest revision of libloadorder, then found that LOOT would no longer see my Skyrim install: this was due to a few corrupted files, so I restored them through Steam, and found that when LOOT was launched through MO it would no longer complain about the empty plugin file.

I guess LOOT must have been using an old revision of libloadorder. I'll close this since it seems to have been a false alarm...

**Comment by WrinklyNinja** [comment]
Re-opening this as I've had a new report of it happening.

**Comment by Geofferic** [comment]
I'm having this exact problem right now with the latest builds.

**Comment by WrinklyNinja** [comment]
I'll look into it this weekend.

**Comment by WrinklyNinja** [comment]
> I'm having this exact problem right now with the latest builds.

I still cannot replicate it, can you give me some detail about what you're doing to experience the issue?

**Comment by WrinklyNinja** [comment]
OK, I can replicate it when the empty plugin is in `plugins.txt` or `loadorder.txt`.

**Comment by WrinklyNinja** [comment]
Fixed as of b3b6d3d1b955d8127ee79a50cbff6dbf424e9004.
