### ISSUE TITLE
Compile the dlls 

### ISSUE THREAD

**Issue by Utumno** [WrinklyNinja/libloadorder#13]
Wrote a wiki article that you may want to incllude in your readme/wiki:

https://github.com/Utumno/libloadorder/wiki/Build-on-windows

For people new to CMake, boost etc this can be handy.

Still I am using MSVC 2013 and when building I get a libloadorder.lib - when I flip the BUILD_SHARED_LIBS flag build fails with:

     1>LINK : fatal error LNK1104: cannot open file 'libboost_filesystem-vc120-mt-sgd-1_56.lib'

So:

1. What is the procedure for generating MSVC solution to build _the dlls_
2. Is it only possible to build on MSVC 2012 ?

Thanks

**Comment by Utumno** [comment]
> What is the procedure for generating MSVC solution to build the dlls

Just select a Release configuration - the  `1>LINK : fatal error LNK1104: cannot open file 'libboost_filesystem-vc120-mt-sgd-1_56.lib'` is thrown in the debug config. This should be in the readme though (or instructions on how to build a debug configuration even better)

> Is it only possible to build on MSVC 2012 ?

No builds fine in MSVS2013 - runs on bash. Still the dll is different size from the one you posted on the https://github.com/wrye-bash/wrye-bash/commit/b79a4c2d23348c8824cc7a22e9b55b37a1abae8b - is this related to the IDE ?

**Comment by WrinklyNinja** [comment]
I'm not interested in providing "how to build Boost and use CMake" instructions, such knowledge is assumed and there are already countless articles available on the web for anyone who needs help with that.
