### ISSUE TITLE
Timestamp load order method should not check for master status

### ISSUE THREAD

**Issue by Utumno** [WrinklyNinja/libloadorder#17]
The pluginComparator class should drop the esm tests. The way it is now a 'corrected' load order is returned to the client but the actual load order (the modification times) stay as they were

EDIT: the reason I want this is twofold - first Bash and liblo do double job in reading the timestamps - if liblo would just return me the timestamps I could easily check for master status. But I see now this will get very tricky - essentially a _cache_and_return_timestamps should be needed. I guess this is too much.
The second reason would be to have more control when setting load order of masters between them - for instance when I flip esm status.

So this probably should be renamed to "expose timestamps cache" cause that is what really is about. Will edit as I get more insight into the API.

**Comment by WrinklyNinja** [comment]
The issue title and description don't match, so I'm not sure if the latest `master` fixes your issue, does it?

**Comment by Utumno** [comment]
Will reopen as needed
