### ISSUE TITLE
Bunch of failed tests (Arch Linux, 64-bit build)

### ISSUE THREAD

**Issue by Freso** [WrinklyNinja/libloadorder#19]
See output at https://gist.github.com/Freso/a7f1c2fee5445dec881a - I don't know whether it is anything to be concerned about, but figured I'd report back in case it's an easy fix. (Maybe it's a Boost 1.59 vs. 1.55 thing, if Travis doesn't complain about it?)

**Comment by WrinklyNinja** [comment]
Did you download and extract the testing plugins like Travis does?

**Comment by WrinklyNinja** [comment]
Closing this as invalid as it seems like the testing plugins simply weren't present.

**Comment by Freso** [comment]
Oops. Yeah. This issue kind of fell under my radar. Will remember to fetch the testing data when I pick this up again. :+1:
