### ISSUE TITLE
MSVS build files broke

### ISSUE THREAD

**Issue by Utumno** [WrinklyNinja/libloadorder#21]
MSVS can't no longer find libespm due to recent changes on master.

**Comment by WrinklyNinja** [comment]
Should be fixed as of 4388dd51b09e6a5e3dec406af27915d14aa6a6ac.

**Comment by Utumno** [comment]
In previous master was fixed if one checked out https://github.com/WrinklyNinja/libespm/commit/8df8873713f39529b150d42805fdc2fd0ba4d63b

Probably fixed now but you should clearly indicate which libespm commit is needed in the commits here (whenever this changes) and in the readme.md

**Comment by WrinklyNinja** [comment]
Looks like I forgot to pin the version used in the Travis configuration too, I'll update that and the readme.

**Comment by WrinklyNinja** [comment]
OK, done and closing this.
