### ISSUE TITLE
Build fails if LaTeX and Doxygen are installed

### ISSUE THREAD

**Issue by Hello71** [WrinklyNinja/libloadorder#32]
afaict there is no `docs/latex/make.bat` and none is ever created.

**Comment by WrinklyNinja** [comment]
Sorry for the late reply, somehow I wasn't watching my own repository so never got an email notification...

I'll look into this, though lately I've switched to using doxygen + breathe + sphinx and letting Read The Docs worry about the LaTeX side of things.

**Comment by neoh4x0r** [comment]
A simple workaround (for now):
Create an empty make.bat file and set it executble
Call make inside the latex folder (this will build refman.pdf)
build the rest of the program
```
$ mkdir build
$ cd build
$ cmake ..
$ cd ../docs/latex/
$ touch make.bat
$ chmod a+x make.bat
$ make
$ cd build
$ make
```

**Comment by Hello71** [comment]
(or just don't build the manual)

**Comment by neoh4x0r** [comment]
@Hello71 
Sure, that could be done -- but would not fix the issue if someone wanted to build the documentation on Linux.

**Comment by WrinklyNinja** [comment]
The `sphinx-docs` branch sidesteps this issue, see the readme for how to build the docs now, any issues with this?

**Comment by WrinklyNinja** [comment]
Closing this as the new documentation isn't build as part of the normal build process, so the issue no longer applies.
