### ISSUE TITLE
Undefined references to several functions

### ISSUE THREAD

**Issue by neoh4x0r** [WrinklyNinja/libloadorder#35]
After following the workaround in #32 (Build fails if LaTeX and Doxygen are installed)
The build continues through to the linking phase and spits out the message below.
This might also be related to #31 (Remove Boost.Locale dependency)

Link to file on dropbox -- because github can't properly display the file:
https://dl.dropboxusercontent.com/u/104054522/skyrim_mods/libloadorder/libloadorder_undefined_references_error.txt

**Comment by WrinklyNinja** [comment]
Looks like you have some ICU references missing, but you've also got

```
libloadorder.cpp:(.text+0x10f): undefined reference to `TLS init function for liblo::extErrorString'
```

which suggests that your compiler doesn't support thread-local storage.

**Comment by neoh4x0r** [comment]
@WrinklyNinja 
I have been trying several different things to debug this issue and I have managed to find the solution.
1) My compiler (gcc-6) fully supports C++14 and thread_local (it seems the issue that caused undefined references to TLS init function was an issue with using std::string instead of const char(
2) the undefined references to ICU were fixed by linking to the ICU libraries

This are the changes that I made to get it to compile without error:
+ Get rid of missing ICU references (also check if compiler support C++14) ....add this to CMakeLists.txt
```
# check that compiler has support for C++14
include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++14" COMPILER_SUPPORTS_CXX14)
if(COMPILER_SUPPORTS_CXX14)
	set(CMAKE_CXX_STANDARD 14)
    message(STATUS "Compiler Support C++14: ${COMPILER_SUPPORTS_CXX14}")
else(COMPILER_SUPPORTS_CXX14)
    message(FATAL_ERROR "Compiler Support C++14: ${COMPILER_SUPPORTS_CXX14}")
endif(COMPILER_SUPPORTS_CXX14)
if (UNIX)
	MESSAGE( STATUS "Building for UNIX" )
	SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -licudata -licui18n -licuio -licule -liculx -licutest -licutu -licuuc")
endif()
```


+ Fix issue with rbeing and rend not being defined....prepend boost:: to rbeing/rend in backend/LoadOrder.cpp
```
boost::rbegin
boost::rend
```
+ Fix undefined reference to TLS init function...in src/api/c_helpers.h & src/api/c_helpers.cpp
```
change the declaration of extErrorString from std::string to const char*
NOTE: this also requires fixing the implentation of string functions for extErrorString in src/api/libloadorder.cpp

if (extErrorString.empty()) => if (extErrorString == "")
 *details = extErrorString.c_str(); => *details = extErrorString;
extErrorString.clear(); => extErrorString = "";
```

**Comment by WrinklyNinja** [comment]
None of those changes should be necessary, and using boost::rbegin and boost::rend is just wrong when you have std::rbegin and std::rend available.

**Comment by neoh4x0r** [comment]
@WrinklyNinja 
Well, that is what was needed to build on my debian/stretch system.

What OS and build system to do you use?

**Comment by WrinklyNinja** [comment]
I personally build on Windows 10, but this repo integrates with Travis CI which is Ubuntu 12.04-based.

**Comment by neoh4x0r** [comment]
@WrinklyNinja 
I can't reproduce the issue with rebgin/rend (I guess that must have been a transient error)

However, it appears that travis.yml is using gcc-5 whereas I am using gcc-6 -- I am not sure if there was any fundamental change to thread_local between those two versions.

**Comment by WrinklyNinja** [comment]
Well, I've now encountered the `undefined reference to `TLS init function for ...` error trying to compile on Debian jessie, so it's not just you. That's with GCC 5.4.1, same as on Travis, so I'm not sure what the difference is.

**Comment by WrinklyNinja** [comment]
Well, the issue doesn't occur if it's built with clang 3.8, so I'm happy with that.

**Comment by WrinklyNinja** [comment]
Closing this as it's no longer relevant with the Rust rewrite.
